### ISSUE TITLE
Release preparation 0.2.17

### ISSUE THREAD

**Issue by fmorgner** [umurmur/umurmur#108]
Current changelog for the upcoming release 0.2.17 a.k.a 'Colin':

Bug fixes and improvements:
- [x] Multiple possible NULL pointer dereferences by @TinnedTuna (#63, #67, #68)
- [x] Set scheduler policy before switching users by @C4K3 (#100)
- [x] Setup TLS infrastructure before switching users by @Nauxuron (#80)
- [x] Default bindport6 to the value of bindport if not set explicitly by @C4K3 (#97 , #101)
- [x] Default to modern TLS suites by @l2dy and @adufray  (#73, #77, #98)
- [x] Fix for leaving garbage when setting socket options by @pfmooney (#83)
- [x] Replace stray bool with bool_t by @andres-erbsen (#70)
- [x] Restrict TLS connections to be TLS >= 1.0 (#84) 

New features:
- [x] Support for mbed TLS >= 2.0 by @Rawi666 with patches by @l2dy (#71, #103, #72, #90)
- [x] New configuration options to hide IP addresses from other users by @C4K3 (#81, #99) 
- [x] Export client hash in SHM interface by @snowblind (#75)
- [ ] New flag (-s) to force switching users (#105, #107, #80)

Deprecations:
- [ ] PolarSSL is not supported any longer

**Comment by hasufell** [comment]
Can we get a release candidate? Most stuff seems settled.

**Comment by fmorgner** [comment]
RC1 has been tagged in 5006685

**Comment by fdutheil** [comment]
Hi,
Is [`tlsi_openssl`: intermediate certificates in certificate file are ignored (#64)] scheduled to be in too? Because it pretty serious (serious as in "throw the whole TLS certificate verification out the window", otherwise).

**Comment by l2dy** [comment]
@fdutheil That commit is in RC1 so yes.

**Comment by C4K3** [comment]
Can we just release? I don't think it makes sense to wait for #105

**Comment by fmorgner** [comment]
I have just tagged 0.2.17. #105 and #104 haven been postponed to 0.2.18. Thanks to all who have participated in making this release possible!
